#!/bin/bash

cp -f "pdf-handout-split/Preface.pdf" "binaries/lec_00_0_preface.pdf"
cp -f "pdf-handout-split/Mathematical Background.pdf" "binaries/lec_00_1_math_background.pdf"
cp -f "pdf-handout-split/Introduction.pdf" "binaries/lec_01_introduction.pdf"
cp -f "pdf-handout-split/Computation and Representation.pdf" "binaries/lec_02_representation.pdf"
cp -f "pdf-handout-split/Defining computation.pdf" "binaries/lec_03_computation.pdf"
cp -f "pdf-handout-split/Syntactic sugar and computing every function.pdf" "binaries/lec_03a_computing_every_function.pdf"
cp -f "pdf-handout-split/Code as data data as code.pdf" "binaries/lec_04_code_and_data.pdf"
# cp -f "pdf-handout-split/Physical implementations of NAND programs.pdf" "binaries/lec_05_physical_implementation.pdf"
cp -f "pdf-handout-split/Loops and infinity.pdf" "binaries/lec_06_loops.pdf"
#cp -f "pdf-handout-split/Indirection and universality.pdf" "binaries/lec_06a_universality.pdf"
cp -f "pdf-handout-split/Equivalent models of computation.pdf" "binaries/lec_07_other_models.pdf"
cp -f "pdf-handout-split/Universality and uncomputability.pdf" "binaries/lec_08_uncomputability.pdf"
cp -f "pdf-handout-split/Restricted computational models.pdf" "binaries/lec_08a_restricted_models.pdf"
cp -f "pdf-handout-split/Is every theorem provable.pdf" "binaries/lec_09_godel.pdf"
cp -f "pdf-handout-split/Efficient computation.pdf" "binaries/lec_10_efficient_alg.pdf"
cp -f "pdf-handout-split/Modeling running time.pdf" "binaries/lec_11_running_time.pdf"
cp -f "pdf-handout-split/Polynomialtime reductions.pdf" "binaries/lec_12_NP.pdf"
cp -f "pdf-handout-split/NP NP completeness and the CookLevin Theorem.pdf" "binaries/lec_13_Cook_Levin.pdf"
cp -f "pdf-handout-split/What if P equals NP.pdf" "binaries/lec_14_PvsNP.pdf"
cp -f "pdf-handout-split/Probability Theory 101.pdf" "binaries/lec_15_probability.pdf"
cp -f "pdf-handout-split/Probabilistic computation.pdf" "binaries/lec_16_randomized_alg.pdf"
cp -f "pdf-handout-split/Modeling randomized computation.pdf" "binaries/lec_17_model_rand.pdf"
cp -f "pdf-handout-split/Cryptography.pdf" "binaries/lec_19_cryptography.pdf"
cp -f "pdf-handout-split/Proofs and algorithms.pdf" "binaries/lec_24_proofs.pdf"
cp -f "pdf-handout-split/Quantum computing.pdf" "binaries/lec_26_quantum_computing.pdf"
cp -f "pdf-handout-split/Space bounded computation.pdf" "binaries/lec_14a_space_complexity.pdf"
cp -f "pdf-handout-split/Contents detailed.pdf" "binaries/contents.pdf"
